# Generated by Django 3.2.20 on 2023-08-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('nome', 'nascimento', 'profissao', 'cidade', 'estado_civil')},
        ),
    ]
