# Generated by Django 3.2.20 on 2023-08-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nascimento',
            new_name='birth',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cidade',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='pais',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profissao',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='estado_civil',
            new_name='relationship',
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('name', 'birth', 'profession', 'city', 'relationship')},
        ),
    ]
